---
- name: Install nginx
  hosts: servers
  remote_user: ubuntu
  become: yes
  tasks:
    - name: install nginx 
      apt: 
        name: nginx 
        state: present
        update_cache: yes
    - name: vim
      apt: 
        name: vim 
        state: present
        update_cache: yes
    - name: net_utils 
      apt: 
        name: net-tools 
        state: present
        update_cache: yes
    
    - name: install iostat
      apt: 
        name: sysstat 
        state: present
        update_cache: yes

- name: install docker 
  hosts: servers
  become: yes
  remote_user: ubuntu
  roles: 
    - geerlingguy.docker
    - geerlingguy.mysql
  tasks:
    - name: create user
      mysql_user:
        name: shaked
        password: 1234
        state: present
        priv: "my_database.*:ALL"

  name: install artifactory
  hosts: servers
  become: yes
  # remote_user: ubuntu
  
  collections:
        - jfrog.platform
  roles:
        - artifactory
  vars:
    artifactory_enabled: true
    #artifactory_home: /opt/jfrog/artifactory

  
