---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: servers
  remote_user: ubuntu
  # remote_user: user
  become: yes

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
