---
    - name: install items
      apt:
        name: "{{ item.name }}"
        state: latest
      with_items:
        - vim
        - net-tools
        - sysstat
        - mysql-client
        - mysql-server
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - software-properties-common

    - name: create users
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        groups: {{ default_groups }}
      loop: "{{ users }}"

    - name: Add sudo rights for deployment users.
      lineinfile:
        dest: /etc/sudoers
        regexp: '^{{ item }}'
        line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'
      loop: "{{ users }}"
